/**
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */

func solveP2() -> Int {
    var last = 1
    var current = 2
    var next = 0
    var evenTotal = 2

    while last + current < 4000000 {
        next = current + last
        last = current
        current = next

        if current % 2 == 0 {
            evenTotal += current
        }
    }
    return evenTotal
}
